version: '3.8'
services:
  backend:
    build: ./backend/
    container_name: mynode
    ports:
      - "4040:4040"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
     - db
     - redis
    environment:
     DB_HOST: db
     DB_PORT: 5432
     DB_USER: myuser
     DB_DATABASE: myuser
     DB_PASSWORD: mypassword
     JWT_SECRET: thapakadshjghji
     MAIL_PASS: gmdvskjwbphdjkor
    links:
      - "redis"

  db:
    image: postgres
    container_name: database_container
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: myuser
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cache_container
    restart: always
    ports:
      - "6379:6379"
  
  frontend:
    build: ./frontend/
    container_name: 'front'
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
     - backend


